<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inc</string>
		<string>asm</string>
		<string>INC</string>
		<string>ASM</string>
	</array>
	<key>name</key>
	<string>Chipsea</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#registers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mnemonics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(;|(^|\s)#\s).*$</string>
					<key>name</key>
					<string>comment.line.string</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.string</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(([0-9]+\.[0-9]*)(e[+-]?[0-9]+)?|\.?[0-9]+e[+-]?[0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.floating-point</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\$[0-9a-f]+)\b</string>
					<key>name</key>
					<string>constant.numeric.literal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b[01]+b\b</string>
					<key>name</key>
					<string>constant.numeric.bin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b[0-7]+[oq]\b</string>
					<key>name</key>
					<string>constant.numeric.oct</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.dec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b([0-9a-fA-F]+[hH]|0x[0-9a-fA-F]+)\b</string>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</array>
		</dict>
		<key>mnemonics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Keyword.other.chipsea</string>
					<key>match</key>
					<string>(?i)\b(addlw|addpcw|addwf|addwfc|andlw|andwf|bcf|bsf|btfsc|btfss|call|clrf|clrwdt|comf|daw)\b</string>
					<key>name</key>
					<string>keyword.control.chipsea.Instruction</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(decf|decfsz|goto|halt|incf|incfsz|iorlw|iorwf|movfw|movlw|movp|movwf|nop|pop|push)\b</string>
					<key>name</key>
					<string>keyword.control.chipsea.Instruction</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(retfie|retlw|return|rlf|rrf|sleep|sublw|subwf|subwfc|swapf|tblp|xorlw|xorwf)\b</string>
					<key>name</key>
					<string>keyword.control.chipsea.Instruction</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(movlf|movff|movff2|movff3|movff4|movff5|movff6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(sublf|subff|subff2|subff3|subff4|subff5|subff6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(addlf|addff|addff2|addff3|addff4|addff5|addff6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(clrf2|clrf3|clrf4|clrf5|clrf6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(rlf2|rlf3|rlf4|rlf5|rlf6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(rrf2|rrf3|rrf4|rrf5|rrf6)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(addfff3|subfff3)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(jz|jnz|jc|jnc|jb|jnb|je|jne)\b</string>
					<key>name</key>
					<string>keyword.operator.chipsea.macro</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*[\#%]\s*if\s+0\b</string>
					<key>end</key>
					<string>(?i)^\s*[\#%]\s*endif\b</string>
					<key>name</key>
					<string>keyword.type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(dw|org|include|end|equ)\b</string>
					<key>name</key>
					<string>keyword.type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(macro|endm|if|endif)\b</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(define)\b</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</array>
		</dict>
		<key>registers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(IND0|IND1|FSR0|FSR1|STATUS|WORK|INTF|INTE|BSR)\b</string>
					<key>name</key>
					<string>support.type.chipsea.system.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(EADRH|EADRL|EDAT|EOPEN|WDTCON|WDTIN|TMOUT|TMCON|ADOH|ADOL|ADOLL|ADCON)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(MCK|PCK|MCK2|NETA|NETB|NETC|NETD|NETE|NETF|SVD|PT1|PT1EN|PT1PU|PT1CON)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(AIENB|PT2|PT2EN|PT2PU|PT4|PT4EN|PT4PU|PT2MR|PT2CON|PTINT|INTF2|INTE2)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(TM0CON|TM0IN|TM0CNT|TM1CON|TM1IN|TM1CNT|TM1R)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LCD1|LCD2|LCD3|LCD4|LCD5|LCD6|LCD7|LCD8|LCD9|LCD10|LCD11|LCD12|lcd13|LCD14)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LED1|LED2|LED3|LED4|LED5|LED6|LED7|LED8|LED9|LED10|LED11|LED12|LED14|LED14)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LEDCON1|LEDCON2|CHPCON|AD2OH|AD2OL)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LCDCN1|LCDENR|TEMPC|WDT_C|IOSC_C|TEST|SCON1|SCON2|SBUF|AIENB)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(RTCCON|RTCAER|RTCYEAR|RTCMON|RTCDAY|RTCHOUR|RTCMIN|RTCSEC|RTCDWR|INTEGER|FRACTION)\b</string>
					<key>name</key>
					<string>support.type.chipsea.special.register</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(Z|C|DC|TO|PD)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(E0IF|E1IF|ADIF|TMIF|AD2IF|TM0IF|TM1IF)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(E0IE|E1IE|ADIE|TMIE|GIE|AD2IE|TM0IE|TM1IE)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(PAGE0|PAGE1|IRP1|IRP0)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(WDTS0|WDTS1|WDTS2|WDTS3|Wdt_lcd|WDTEN|WDTS_0|WDTS_1|WDTS_2)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(INS0|INS1|INS2|TMEN|TRST)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ADM0|ADM1|ADM2|ADSC|ADM_0|ADM_1|ADM_2)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(M1_CK|M2_CK)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(S_BEEP0|S_BEEP1|LCDSCKS0|LCDSCKS1|LCDSCKS2|LCDSCKS3)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(CLK_SEL|M3_CK|EO_SLP|CST_IN|CST_E|XTALSEL|TMSEL0|TMSEL1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(CHPCKS0|CHPCKS1|CHPCKS2|CM_SEL|SINL_0|SINL_1|ACM|SINL0|SINL1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ERV)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ADEN|ADG0|ADG_0|ADG_1|ADG1|ADG_M0|ADG_M1|CHOPM0|CHOPM1|CHOPM_0|CHOPM_1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LCDREF0|LCDREF1|VLCDX0|VLCDX1|Level_s|LCDCH)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ENLB|SILB0|SILB1|SILB2|LDOS0|LDOS1|LB_RST_CON|SILB_0|SILB_1|SILB_2|LDOS_0|LDOS_1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ENVB|BGID0|BGID1|BGID2|BGID3|ENVDDA|LDOEN|LVR_EN|CHP_VPP)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LBOUT)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(AIENB1|AIENB2|AIENB3)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(E0M0|E0M1|E1M0|E1M1|E0M_0|E0M_1|E1M_0|E1M_1|BZEN)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(BZSEL|SEGCON0|SEGCON1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(PTW0_0|PTW0_1|PTW0_2|PTW1_0|PTW1_1|PTW1_2|PTW1_3)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(URRIF|URTIF|RTCIF)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(URRIE|URTIE|RTCIE)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(T0SEL|T0RSTB|T0RATE_0|T0RATE_1|T0RATE_2|T0EN)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(PWM1OUT|T1OUT|T1RSTB|T1CKS|T1RATE_0|T1RATE_1|T1RATE_2|T1EN)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LED_PMODE|LEDCLKS_0|LEDCLKS_1|LED_DUTY0|LED_DUTY1|LED_DUTY2|LED_Current0|LED_Current1|LED_Current2)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(LEDEN|CONT_SEL)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(CSE_LCD)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(CHPEN|CHPCLKS_0|CHPCLKS_1|CHPCLKS_2|CHPVS)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(AD2EN)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(RTCEN|H_24_12|LIR)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(DWR_0|DWR_1|DWR_2)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ENPMPL|LCD_DUTY0|LCD_DUTY1|LEVEL|LCDWS|LCDEN|LCDCKS0|LCDCKS1)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(WDT_C1|WDT_C2|WDT_C3)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(UARTEN|UART_SEL|RB8|TB8|REN|SM2|SM1|SM0)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(SMOD)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(W|F)\b</string>
					<key>name</key>
					<string>support.constant.chipsea.sfr.bitmap</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(%%)?(\w|[\._?])(\w|[_$#@~\.?])*\:</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*([$@~])(\w|[_$#@~\.?])*\:</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.chipsea.assembly</string>
	<key>uuid</key>
	<string>6157814c-5c11-4dcf-8d6f-c550b8a8d11a</string>
</dict>
</plist>
